### PR TITLE
Allow two or more StyledTextAreas (View) to share the same StyledDocument (Model)

### PR DESCRIPTION
**Pull request by JordanMartinez**
I implemented the approach I described in #152 and for the most part it works. There are a few problems.
- If the user types in the original area quickly or if the user types even one character in the second line in the original area, the original area making the modification throws a StringIndexOutOfBoundsException.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Here's the stacktrace:
````java
Exception in thread "JavaFX Application Thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -82
	at java.lang.String.substring(String.java:1967)
	at org.fxmisc.richtext.Paragraph.substring(Paragraph.java:73)
	at org.fxmisc.richtext.StyledDocumentBase.sub(StyledDocumentBase.java:245)
	at org.fxmisc.richtext.StyledDocumentBase.getText(StyledDocumentBase.java:51)
	at org.fxmisc.richtext.StyledDocumentBase.getText(StyledDocumentBase.java:46)
	at org.fxmisc.richtext.StyledTextArea.lambda$new$4(StyledTextArea.java:615)
	at org.reactfx.value.Val$2.computeValue(Val.java:703)
	at org.reactfx.value.ValBase.getValue(ValBase.java:17)
	at org.reactfx.value.SuspendableValWrapper.getValue(SuspendableValWrapper.java:23)
	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:765)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$281(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.SuspendableBase.handleEvent(SuspendableBase.java:82)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$278(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$281(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.value.ValBase.invalidate(ValBase.java:32)
	at org.reactfx.value.Val$2.lambda$connect$136(Val.java:689)
	at com.sun.javafx.collections.ListListenerHelper$SingleInvalidation.fireValueChangedEvent(ListListenerHelper.java:126)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$52(FXCollections.java:929)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase$SubObservableList.clear(ModifiableObservableListBase.java:346)
	at org.fxmisc.richtext.EditableStyledDocument.setAll(EditableStyledDocument.java:450)
	at org.fxmisc.richtext.EditableStyledDocument.replace(EditableStyledDocument.java:206)
	at org.fxmisc.richtext.StyledTextArea.replace(StyledTextArea.java:1127)
	at org.fxmisc.richtext.StyledTextArea.replaceText(StyledTextArea.java:1118)
	at org.fxmisc.richtext.TextEditingArea.replaceText(TextEditingArea.java:205)
	at org.fxmisc.richtext.EditActions.replaceSelection(EditActions.java:119)
	at org.fxmisc.richtext.StyledTextAreaBehavior.keyTyped(StyledTextAreaBehavior.java:312)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$null$23(EventHandlerTemplate.java:156)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$act$24(EventHandlerTemplate.java:155)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$Builder.lambda$create$21(EventHandlerTemplate.java:117)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$17(EventHandlerTemplate.java:39)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$bind$14(EventHandlerTemplate.java:18)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$353(GlassViewEventHandler.java:228)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by TomasMikula** [comment]
`retainLatestWhen(condition)` behaves normally when `condition` is `false`, and forgets all incoming events except the latest when `condition` is `true`. So `retainLatestWhen(notBeingUpdated)` will be forgetting events when not being updated. Probably not what you wanted. You probably wanted `retainLatestWhen(beingUpdated)`. But I wouldn't use anything that has the potential of silently ignoring events here. It seems to me though that you can omit this call completely, can't you?

**Comment by JordanMartinez** [comment]
My goal was to only update the carets and selection ranges of the Areas that weren't doing the modification. Otherwise, if one types some keys and inserts text, the area who's modifying the document would increment its caret position twice. So, I thought that if an Area was modifying the document via user interaction, `beingUpdated` would be suspended and thus could be used to only update the other areas and not the one modifying it.
Thinking about it now, you're right: using `beingUpdated` rather than `notBeingUpdated` is the correct way to do it, so I'm not sure why I didn't do it that way, lol...

**Comment by JordanMartinez** [comment]
You're right again: removing the `retainLatest` part doesn't increment an area's caretPosition twice.

**Comment by JordanMartinez** [comment]
However, I still get that `StringIndexOutOfBoundsException` :frowning:

**Comment by TomasMikula** [comment]
Let's move 

```java
private final SuspendableNo beingUpdated = new SuspendableNo();
```

to EditableStyledDocument, but keep using it from the StyledTextAreas. This way we can ensure that the published updates are consistent, even when made by the other area.

**Comment by JordanMartinez** [comment]
How's that?

**Comment by TomasMikula** [comment]
Did it resolve the problem?

**Comment by JordanMartinez** [comment]
Nope :-/

**Comment by JordanMartinez** [comment]
However, I have noticed something that might help pinpoint the problem. If I put the top area's caret at the beginning of the area and start inserting a letter via KeyTyped events, the problem will only occur after I've typed in so many keys. 

Also, if I comment out the line in CloneDemo:
````java
clone.selectRange(selectionStart, selectionEnd);
````
then the problem doesn't arise as long as I don't click into the clone. I can type as many letters as I want and the problem won't arise no matter where the initial caret is when I type something.

**Comment by TomasMikula** [comment]
Ah, the individual properties and streams are still being suspended manually, so they don't get suspended when the document is being updated from the other area. So we need to rewrite the suspension of those to be suspended automatically when `beingUpdated` is true, instead of suspending them manually when suspending `beingUpdated`.

**Comment by JordanMartinez** [comment]
I'm looking at [the lines that follow `content.replace`](https://github.com/TomasMikula/RichTextFX/pull/231/files#diff-5e6fcbe2053b1e1acfcb2f4f7c0606adR1140). When the above exception does get fixed, won't this cause the caretPosition of the area that does the modification to be incremented twice?

**Comment by TomasMikula** [comment]
No. The caret position will be set to the new value twice, but that's OK.

**Comment by TomasMikula** [comment]
So what I proposed can have the unwanted effect that the user could observe a change while `beingUpdated` was `false`... :/

**Comment by JordanMartinez** [comment]
:-/ bummer....

If I'm understanding how this process works...
When one area makes a modification to the document, it suspends all of its' suspendable objects (selectedText, caretPosition, etc.) and makes the underlying change. Once that gets changed, it unsuspends those objects in a specific order. Once unsuspended, these suspendables emit the updated value. Using this suspendable process guarantees that anything bound to them always have a valid and correct value, correct?

The SIOOBE above occurs because one document modifies the document, and thus suspends its suspendables, but the other one doesn't. So, any change that one area does will immediately be pushed to the clone's suspendables, which will emit the resulting value, thus breaking this guarantee of an always-valid-and-correct-value contract, right?

**Comment by TomasMikula** [comment]
Yes, that's exactly how it works.

**Comment by JordanMartinez** [comment]
> So what I proposed can have the unwanted effect that the user could observe a change while beingUpdated was false... :/

Can you further explain this?

**Comment by JordanMartinez** [comment]
So, we have to figure out how to suspend the suspendables of all areas that are using the same `EditableStyledDocument` when any one of them makes a change to that document.

**Comment by JordanMartinez** [comment]
What about moving a variation of `omniSuspendable` to `EditableStyledDocument`?

The document could have a list where each entry is an attached area's omniSuspendable object and each area has access to the document's method `suspendAll` that suspends all of the document's omniSuspendables so one area can make a change.

**Comment by JordanMartinez** [comment]
Yeah.. doing that makes it work now.

**Comment by JordanMartinez** [comment]
I'm not sure if that fixed every problem, I got another SIOOBE when messing around with the CloneDemo.

**Comment by JordanMartinez** [comment]
Yup, I can get another SIOOBE when I position clone's caret at the end of the area and then delete a character in the original area.

**Comment by JordanMartinez** [comment]
K, I think we're good to go.
If you think the list of OmniSuspendable objects is a good idea, should it be implemented differently? I feel like there should be some convenient method that is similar to the try-with-resource block that was used before this.

**Comment by JordanMartinez** [comment]
I'm headed off to bed now. Be back on Monday.

**Comment by JordanMartinez** [comment]
With my idea of storing each connected `StyledTextArea`'s omniSuspendable object in `EditableStyledDocument`, and the approach of storing their `Guard`s in a temporary list until later closing, will this still work if two areas make a change at the same time?

In other words, will the process go like this (what my approach expects):
1. First area suspends everything; `guards` stores the Guard objects returned from suspending all area's omniSuspendables
2. Second area wants to suspend everything, but can't because things are already suspended.
3. First area finishes updating document and unsuspends everything.
4. Second area can now re-suspend everything and make its changes before unsuspendeding everything.

or like this:
1. First area suspends everything; `guards` stores the Guard objects returned from suspending all area's omniSuspendables
2. Second area suspends everything; `guards`, which holds first suspensions' Guard objects, is "cleared" due to being assigned a new `ArrayList`. Second area finishes making update and closes its Guard objects.
3. First area may finish making updates, but since references to its returned Guard objects are gone, it cannot unsuspend everything.

**Comment by JordanMartinez** [comment]
If ReactFX's `Suspendable.combine()` could take a `List<Suspendable>` argument, then I could reimplement the try-with-resource block originally used:
````java
try (Guard g = content.suspendAll()) {
    // updates
}
````
where suspendAll would be
````java
private List<Suspendable> suspendables;

Guard suspendAll() {
    return Suspendable.combine(suspendables).suspend();
}
````

**Comment by JordanMartinez** [comment]
I've opened up another PR with a cleaner commit history of this branch for merging if you're good with this. Otherwise, let's continue our discussion here and I'll close the newer one.

**Comment by TomasMikula** [comment]
Just a heads up, I'm traveling these days. Will get back to this in a few
days.

**Comment by JordanMartinez** [comment]
Thanks for the heads up. Safe travels man!

**Pull request closed without merging**
