### PR TITLE
Exposes DragState so subclasses can more easily override drag-related event handling

### PR DESCRIPTION
**Pull request by JordanMartinez**
Proposed fix to #223

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Hmm... If this gets merged, then we've already started down the path of not finishing the MVC refactoring. If it doesn't, then I'm stuck rewriting the code you've already written or dropping a necessary feature...

I guess that means I now have a reason to finish the refactoring, lol...

**Comment by TomasMikula** [comment]
Sorry for not being responsive. I've been buried under lots of other work.

I came up with `DragState` et al. without giving it too much thought and I'm not quite comfortable putting it to the public API (without giving it additional thought). An API that maybe exposes less implementation details and gives you the feature that you need would be to have

```java
Property<IntConsumer> onSelectionDrop();
```

that let's you override what to do on mouse release when dragging the selection. The `int` would be the insertion index where the mouse was released. The default would be  `i -> area.moveSelectedText(i)`, but could be overridden. How does it sound?

**Comment by JordanMartinez** [comment]
No worries man! I figured you had finals-related stuff or something going on...

Ok, I'll look into that more and get back to you.

**Comment by JordanMartinez** [comment]
See PR 228

**Pull request closed without merging**
