### PR TITLE
Use the -rtfx prefix for RichTextFX specific underline properties, us…

### PR DESCRIPTION
**Pull request by afester**
…e the underline width as the toggle to enable/disable the underline

### CODE REVIEW

**Comment by TomasMikula** [comment]
Cool, thanks!

**Comment by JordanMartinez** [comment]
I've updated the CSS guide to use the updated prefix.

**Comment by TomasMikula** [comment]
Great, thanks @JordanMartinez !

**Comment by JordanMartinez** [comment]
No problem!

Quick question @TomasMikula `TextExt` also has the CSS property `-fx-background-fill`. Could you clarify: is this used internally (and thus shouldn't be included in the guide) or another part of the text that can be styled (and thus should be in the guide and also use the `-rtfx` prefix)?

**Comment by TomasMikula** [comment]
Good catch! It _is_ meant to be used by users. So it should be renamed to `-rtfx` and included in the guide. At that occasion, we might as well rename it to `-rtfx-background-color`, since the only reason it was called `-fill` instead of `-color` was [JDK-8133685](https://bugs.openjdk.java.net/browse/JDK-8133685).

**Pull request merged**
