### PR TITLE
Issue-584: Fixed sub sequence when the resulting sub sequence will be…

### PR DESCRIPTION
**Pull request by afester**
… empty

### CODE REVIEW

**Comment by JFormDesigner** [comment]
I think this needs more investigation because this PR would undo PR #578 which fixes #573

**Comment by afester** [comment]
Thanks for the link to #573 - will check that ...

**Comment by JordanMartinez** [comment]
The issue that arises both in #573 and #584 is the fact that a style is still associated with an empty segment. Thus, one cannot use a singleton empty segment throughout the area when referring to an empty one because of the style. If you do, it messes up the undo/redo system (e.g. `Unexpected change received: Expected StyledText[text="" style=null] Actual StyledText[text="" style=]`. See also my comments from the Hyperlink demo PR [here](https://github.com/TomasMikula/RichTextFX/pull/550#discussion_r132587029) and [here](https://github.com/TomasMikula/RichTextFX/pull/550#discussion_r132762944)

Again, this is why I'm proposing #567 as then we could have algerbraic data types: an empty and non-empty segment that can be created, subsequenced, etc. without needing the know anything about its style.
The real issue is that `Paragraph` doesn't have a way to know what style it should use when creating an empty segment. If it's the first paragraph in the area, it should default to `initialTextStyle`. If it's in the middle, it should default to the style stored at the last part in the preceding paragraph.

**Comment by afester** [comment]
This requires some more investigation and also integration tests should be provided for #573 and #584 .

**Comment by JordanMartinez** [comment]
@afester Can you write a test that shows the error arising? If you're not familiar with TestFX, you can write a sample JavaFX App and then list comments as to what is supposed to happen once the stage is shown. Then, I can convert it into a TestFX test.

**Pull request closed without merging**
