### PR TITLE
Exposed Scrolling API for StyledTextArea

### PR DESCRIPTION
**Pull request by JordanMartinez**

### CODE REVIEW

**Comment by TomasMikula** [comment]
Looking good. Maybe add comments that `total*Estimate` properties are only supposed to be _set_ by the skin, not the user, and that `estimatedScroll*` can be set in order to scroll the content.

**Comment by JordanMartinez** [comment]
Should I add those comments in the class javadoc or the property's javadoc ?

**Comment by TomasMikula** [comment]
I think property's javadoc is better.

**Comment by JordanMartinez** [comment]
How's that?

**Comment by TomasMikula** [comment]
:+1:

**Pull request merged**
