### PR TITLE
Skin removal

### PR DESCRIPTION
**Pull request by JordanMartinez**
This one's cleaner.

### CODE REVIEW

**Comment by TomasMikula** [comment]
Is there something lost from `StyledTextAreaView` or `StyledTextAreaVisual`, when you keep them around?

**Comment by JordanMartinez** [comment]
> Is there something lost from StyledTextAreaView or StyledTextAreaVisual, when you keep them around?

I don't think so. I just didn't see the need to have them anymore, so I deleted them. Should I leave them there and just deprecate them?

**Comment by TomasMikula** [comment]
No, sorry, I was looking at the commit where you inlined StyledTextAreaView and was wondering why you kept the original file around. Didn't realize you deleted it in the next commit.

**Comment by JordanMartinez** [comment]
Oh ok... 
Looking back at them now, if I don't delete them, I get issues in `StyledTextAreaView` when trying to access CharacterHit because it's no longer in the skin package and I'm guessing you don't want it public.

**Comment by TomasMikula** [comment]
Seems like the `dispose()` method is no longer needed. The Skin had to be disposed to stop observing the Control. Now the "control" is only observing itself (its own properties and its own `EditableStyledDocument`), so disposal is not necessary.

(In the future I would like to be able to provide an external document. At that point, dispose will need to be reintroduced to break ties with the document, if the document outlives the area.)

If you don't see any catch, we can remove the method. That also means we don't need to keep the subscriptions that are unsubscribed in `dispose()`.

**Comment by JordanMartinez** [comment]
> Seems like the dispose() method is no longer needed. 

Yeah, I was wondering about that...

Looking at its dependencies, would I remove all of the following?
- Subscription subscription = () -> {};
- manageSubscription()
- manageBinding()
- subscribeTo()

and then change all `subscribeTo()` to `stream.subscribe( /* code */);` and delete all `manageBinding()` references.

> (In the future I would like to be able to provide an external document. At that point, dispose will need to be reintroduced to break ties with the document, if the document outlives the area.)

Yeah, the idea proposed in #152.

**Comment by TomasMikula** [comment]
One more thing. Seems like `StyledTextAreaBehavior` doesn't need a direct reference to `VirtualFlow`. In the two places it is used, `area` can be used just as well.

**Comment by JordanMartinez** [comment]
I was thinking it would be more precise if `VirtualFlow` was used. But then again, if it's the only child, I guess it doesn't really matter....

**Comment by TomasMikula** [comment]
This was a lot of work, thanks!

**Comment by JordanMartinez** [comment]
Woohoo!

**Pull request merged**
