### PR TITLE
Handle drag events only if mouse release occurred inside of view

### LINKED ISSUE #321: Unexpected text drag behavior on abort.
Hi Tomas

When dragging text and the mouse is release outside of the control then the selected text is moved generally to the beginning of the text area or some earlier location in the text.

The expected behavior I believe is that the drag should be aborted and the text should not move.

Thanks, regards
Jurgen

### PR DESCRIPTION
**Pull request by JordanMartinez**
This should fix #321

### CODE REVIEW

**Comment by TomasMikula** [comment]
Shouldn't the test be inside of the `DRAG` case?

**Comment by JordanMartinez** [comment]
> Shouldn't the test be inside of the DRAG case?

The caret will still move then, but that's what happens in a TextArea, too, (just tested it). So, yeah, it should.

**Comment by JordanMartinez** [comment]
I've updated the PR

**Comment by TomasMikula** [comment]
👍

**Pull request merged**
