### PR TITLE
Revert to previous merge method

### PR DESCRIPTION
**Pull request by JordanMartinez**
Reverts back to the previous merge method

### CODE REVIEW

**Comment by TomasMikula** [comment]
The type param on `UndoActions` should not be necessary.

**Comment by JordanMartinez** [comment]
As said in my other comment, should the `TextChange` class-to-interface conversion be done at all? If it should, I feel like it should be in its own PR that does a lot of other refactoring.

**Comment by TomasMikula** [comment]
Yeah, not in this PR. Not sure what it gives us anyway.

**Comment by JordanMartinez** [comment]
Not really anything. It was only necessary because of my error in adding a type param to `UndoActions`

I'll fix this tomorrow.

**Comment by JordanMartinez** [comment]
Ok. Only the revert is in this PR now.

**Pull request merged**
